# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "github.com/BurntSushi/toml";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/toml";
      rev = "a368813c5e648fee92e5f6c30e3944ff9d5e8895";
      sha256 = "1sjxs2lwc8jpln80s4rlzp7nprbcljhy5mz4rf9995gq93wqnym5";
    };
  }
  {
    goPackagePath = "github.com/PuerkitoBio/purell";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/purell";
      rev = "0bcb03f4b4d0a9428594752bd2a3b9aa0a9d4bd4";
      sha256 = "0vsxyn1fbm7g873b8kf3hcsgqgncb5nmfq3zfsc35a9yhzarka91";
    };
  }
  {
    goPackagePath = "github.com/PuerkitoBio/urlesc";
    fetch = {
      type = "git";
      url = "https://github.com/PuerkitoBio/urlesc";
      rev = "de5bf2ad457846296e2031421a34e2568e304e35";
      sha256 = "0n0srpqwbaan1wrhh2b7ysz543pjs1xw2rghvqyffg9l0g8kzgcw";
    };
  }
  {
    goPackagePath = "github.com/alecthomas/chroma";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/chroma";
      rev = "03b0c0d6bb7b9f7f8fd58fca6f1c6a2caffb9ca8";
      sha256 = "0xnvl8d12nc7liy90hzxdkf5n12ph8ch28lhy2ar3f1adxdza7z0";
    };
  }
  {
    goPackagePath = "github.com/bep/gitmap";
    fetch = {
      type = "git";
      url = "https://github.com/bep/gitmap";
      rev = "de8030ebafb76c6e84d50ee6d143382637c00598";
      sha256 = "0adkv2ghi0zd104akksa9wjzj7s849wpa1rij03mycgxp4si9ami";
    };
  }
  {
    goPackagePath = "github.com/chaseadamsio/goorgeous";
    fetch = {
      type = "git";
      url = "https://github.com/chaseadamsio/goorgeous";
      rev = "7daffad08e0d467847663af3655dcc4cbcda48e8";
      sha256 = "10a7n5d3bhfha6r55z9y01ymcnxkccdypzdzp99ws5gmmg4v6ycy";
    };
  }
  {
    goPackagePath = "github.com/cpuguy83/go-md2man";
    fetch = {
      type = "git";
      url = "https://github.com/cpuguy83/go-md2man";
      rev = "1d903dcb749992f3741d744c0f8376b4bd7eb3e1";
      sha256 = "1p1ncq4vv244w9v144vplsb2vbl3369wdxn4gc7xbfafkjwn8bxc";
    };
  }
  {
    goPackagePath = "github.com/danwakefield/fnmatch";
    fetch = {
      type = "git";
      url = "https://github.com/danwakefield/fnmatch";
      rev = "cbb64ac3d964b81592e64f957ad53df015803288";
      sha256 = "0cbf511ppsa6hf59mdl7nbyn2b2n71y0bpkzbmfkdqjhanqh1lqz";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "346938d642f2ec3594ed81d874461961cd0faa76";
      sha256 = "0d4jfmak5p6lb7n2r6yvf5p1zcw0l8j74kn55ghvr7zr7b7axm6c";
    };
  }
  {
    goPackagePath = "github.com/dchest/cssmin";
    fetch = {
      type = "git";
      url = "https://github.com/dchest/cssmin";
      rev = "fb8d9b44afdc258bfff6052d3667521babcb2239";
      sha256 = "09sdijfx5d05z4cd5k6lhl7k3kbpdf2amzlngv15h5v0fff9qw4s";
    };
  }
  {
    goPackagePath = "github.com/dlclark/regexp2";
    fetch = {
      type = "git";
      url = "https://github.com/dlclark/regexp2";
      rev = "487489b64fb796de2e55f4e8a4ad1e145f80e957";
      sha256 = "144s81ndviwhyy20ipxvvfvap8phv5p762glxrz6aqxprkxfarj5";
    };
  }
  {
    goPackagePath = "github.com/eknkc/amber";
    fetch = {
      type = "git";
      url = "https://github.com/eknkc/amber";
      rev = "cdade1c073850f4ffc70a829e31235ea6892853b";
      sha256 = "152w97yckwncgw7lwjvgd8d00wy6y0nxzlvx72kl7nqqxs9vhxd9";
    };
  }
  {
    goPackagePath = "github.com/fortytw2/leaktest";
    fetch = {
      type = "git";
      url = "https://github.com/fortytw2/leaktest";
      rev = "7dad53304f9614c1c365755c1176a8e876fee3e8";
      sha256 = "1f2pmzs0dgayg0q672cpzxqa1ls48aha262qxlglihdvami53b2m";
    };
  }
  {
    goPackagePath = "github.com/fsnotify/fsnotify";
    fetch = {
      type = "git";
      url = "https://github.com/fsnotify/fsnotify";
      rev = "629574ca2a5df945712d3079857300b5e4da0236";
      sha256 = "06wfg1mmzjj04z7d0q1x2fai9k6hm957brngsaf02fa9a3qqanv3";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "ea4d1f681babbce9545c9c5f3d5194a789c89f5b";
      sha256 = "1bhgs2542qs49p1dafybqxfs2qc072xv41w5nswyrknwyjxxs2a1";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-immutable-radix";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-immutable-radix";
      rev = "8aac2701530899b64bdea735a1de8da899815220";
      sha256 = "032w4pk4gd5lwwgnvhh52xnrgyp7lgmlxsfs47gnxkgkya1x7lw6";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/golang-lru";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/golang-lru";
      rev = "0a025b7e63adc15a622f29b0b2c4c3848243bbf6";
      sha256 = "1iq7lbpsz7ks052mpznmkf8s4k43p51z4dik2n9ivrxk666q2wxi";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "23c074d0eceb2b8a5bfdbb271ab780cde70f05a8";
      sha256 = "0db4lpqb5m130rmfy3s3gjjf4dxllypmyrzxv6ggqhkmwmc7w4mc";
    };
  }
  {
    goPackagePath = "github.com/inconshreveable/mousetrap";
    fetch = {
      type = "git";
      url = "https://github.com/inconshreveable/mousetrap";
      rev = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75";
      sha256 = "1mn0kg48xkd74brf48qf5hzp0bc6g8cf5a77w895rl3qnlpfw152";
    };
  }
  {
    goPackagePath = "github.com/jdkato/prose";
    fetch = {
      type = "git";
      url = "https://github.com/jdkato/prose";
      rev = "20d3663d4bc9dd10d75abcde9d92e04b4861c674";
      sha256 = "1gjqgrpc7wbqvnhgwyfhxng24qvx37qjy0x2mbikiw1vaygxqsmy";
    };
  }
  {
    goPackagePath = "github.com/kardianos/osext";
    fetch = {
      type = "git";
      url = "https://github.com/kardianos/osext";
      rev = "ae77be60afb1dcacde03767a8c37337fad28ac14";
      sha256 = "056dkgxrqjj5r18bnc3knlpgdz5p3yvp12y4y978hnsfhwaqvbjz";
    };
  }
  {
    goPackagePath = "github.com/kyokomi/emoji";
    fetch = {
      type = "git";
      url = "https://github.com/kyokomi/emoji";
      rev = "7e06b236c489543f53868841f188a294e3383eab";
      sha256 = "1q2j0k5a8qqka1syc9zwmf1cvm6k628kf2g1nmghp2kdr7q1xmyb";
    };
  }
  {
    goPackagePath = "github.com/magefile/mage";
    fetch = {
      type = "git";
      url = "https://github.com/magefile/mage";
      rev = "2f974307b636f59c13b88704cf350a4772fef271";
      sha256 = "06afqyivnl5xja497kcck5984d6bcpsbq88n8qvl7if9qifxzqdm";
    };
  }
  {
    goPackagePath = "github.com/magiconair/properties";
    fetch = {
      type = "git";
      url = "https://github.com/magiconair/properties";
      rev = "be5ece7dd465ab0765a9682137865547526d1dfb";
      sha256 = "0spk58x9b0hj29cw6wy6rlvc6s9xk4r0gmlxgsc194pkzqcg1my8";
    };
  }
  {
    goPackagePath = "github.com/markbates/inflect";
    fetch = {
      type = "git";
      url = "https://github.com/markbates/inflect";
      rev = "ea17041f342f81e8849284b87bc3db1a6fc596bb";
      sha256 = "15zd3sagcyi0d8myypydpg21nvff1j9n5smzx1k5vyvxq0474z4d";
    };
  }
  {
    goPackagePath = "github.com/miekg/mmark";
    fetch = {
      type = "git";
      url = "https://github.com/miekg/mmark";
      rev = "fd2f6c1403b37925bd7fe13af05853b8ae58ee5f";
      sha256 = "0q2zrwa2vwk7a0zhmi000zpqrc01zssrj9c5n3573rg68fksg77m";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "06020f85339e21b2478f756a78e295255ffa4d6a";
      sha256 = "12zb5jh7ri4vna3f24y9g10nzrnz9wbvwnk29wjk3vg0ljia64s9";
    };
  }
  {
    goPackagePath = "github.com/nicksnyder/go-i18n";
    fetch = {
      type = "git";
      url = "https://github.com/nicksnyder/go-i18n";
      rev = "ca33e78c8a430e2df435b02f63a3944fa8e9ea11";
      sha256 = "1iag6q8ysbra0zlxi7n81q8b4nqhh0jnlvrhfwcdmli42bczdz3q";
    };
  }
  {
    goPackagePath = "github.com/pelletier/go-toml";
    fetch = {
      type = "git";
      url = "https://github.com/pelletier/go-toml";
      rev = "16398bac157da96aa88f98a2df640c7f32af1da2";
      sha256 = "18a63z1a492618ab4ad3xqlpl8rck42jrnci5klf7lgn0ky9000g";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "792786c7400a136282c1664665ae0a8db921c6c2";
      sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
    };
  }
  {
    goPackagePath = "github.com/russross/blackfriday";
    fetch = {
      type = "git";
      url = "https://github.com/russross/blackfriday";
      rev = "4048872b16cc0fc2c5fd9eacf0ed2c2fedaa0c8c";
      sha256 = "17zg26ia43c8axrxp5q2bxh1asiqfhin4ah7h5d8ibil6pv7xbx4";
    };
  }
  {
    goPackagePath = "github.com/shurcooL/sanitized_anchor_name";
    fetch = {
      type = "git";
      url = "https://github.com/shurcooL/sanitized_anchor_name";
      rev = "86672fcb3f950f35f2e675df2240550f2a50762f";
      sha256 = "142m507s9971cl8qdmbcw7sqxnkgi3xqd8wzvfq15p0w7w8i4a3h";
    };
  }
  {
    goPackagePath = "github.com/spf13/afero";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/afero";
      rev = "5660eeed305fe5f69c8fc6cf899132a459a97064";
      sha256 = "0rpwvjp9xfmy2yvbmy810qamjhimr56zydvx7hb1gjn3b7jp4rhd";
    };
  }
  {
    goPackagePath = "github.com/spf13/cast";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cast";
      rev = "acbeb36b902d72a7a4c18e8f3241075e7ab763e4";
      sha256 = "0w25s6gjbbwv47b9208hysyqqphd6pib3d2phg24mjy4wigkm050";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "7b2c5ac9fc04fc5efafb60700713d4fa609b777b";
      sha256 = "0k4xswdfd2ridj7m48ijb4klq9mxpw03g8h2rvq99yddi8vmlbvn";
    };
  }
  {
    goPackagePath = "github.com/spf13/fsync";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/fsync";
      rev = "12a01e648f05a938100a26858d2d59a120307a18";
      sha256 = "1vvbgxbbsc4mvi1axgqgn9pzjz1p495dsmwpc7mr8qxh8f6s0nhv";
    };
  }
  {
    goPackagePath = "github.com/spf13/jwalterweatherman";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/jwalterweatherman";
      rev = "12bd96e66386c1960ab0f74ced1362f66f552f7b";
      sha256 = "1abvqd1dl3m7mxv44wvl0vwd50l6qpndzrxk28vyb77x41rc8b2g";
    };
  }
  {
    goPackagePath = "github.com/spf13/nitro";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/nitro";
      rev = "24d7ef30a12da0bdc5e2eb370a79c659ddccf0e8";
      sha256 = "143sbpx0jdgf8f8ayv51x6l4jg6cnv6nps6n60qxhx4vd90s6mib";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "e57e3eeb33f795204c1ca35f56c44f83227c6e66";
      sha256 = "13mhx4i913jil32j295m3a36jzvq1y64xig0naadiz7q9ja011r2";
    };
  }
  {
    goPackagePath = "github.com/spf13/viper";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/viper";
      rev = "25b30aa063fc18e48662b86996252eabdcf2f0c7";
      sha256 = "1a1xxsn39sgiyhz3pd9v5qhi7d5p4z4cml0mcdgm65n3f8vgkdv3";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "69483b4bd14f5845b5a1e55bca19e954e827f1d0";
      sha256 = "11lzrwkdzdd8yyag92akncc008h2f9d1bpc489mxiwp0jrmz4ivb";
    };
  }
  {
    goPackagePath = "github.com/yosssi/ace";
    fetch = {
      type = "git";
      url = "https://github.com/yosssi/ace";
      rev = "ea038f4770b6746c3f8f84f14fa60d9fe1205b56";
      sha256 = "1kbvbc56grrpnl65grygd23gyn3nkkhxdg8awhzkjmd0cvki8w1f";
    };
  }
  {
    goPackagePath = "golang.org/x/image";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/image";
      rev = "f7e31b4ea2e3413ab91b4e7d2dc83e5f8d19a44c";
      sha256 = "1ck1ri64v10f4fprbs98dyk7pnm3kfb10kbsdv83b11fy1zzsy1f";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "cd69bc3fc700721b709c3a59e16e24c67b58f6ff";
      sha256 = "103kv0ghx01c1cb9cp1hc6kgccrlh45b09f842mk0p2znslbcgr0";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "8dbc5d05d6edcc104950cc299a1ce6641235bc86";
      sha256 = "1ay74gwxfzy5h5wsgmd74shbm93y6xb73qbpbw2ff928s9q4xb7b";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "c01e4764d870b77f8abe5096ee19ad20d80e8075";
      sha256 = "1nqxkw0g7kfycgajpj8cgwhnq4g0jr4g72n1d6fjp0r600izqwcc";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "eb3733d160e74a9c7e442f435eb3bea458e1d19f";
      sha256 = "1srhvcaa9db3a6xj29mkjr5kg33y71pclrlx4vcwz5m1lgb5c7q6";
    };
  }
]
