# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "github.com/AndreasBriese/bbloom";
    fetch = {
      type = "git";
      url = "https://github.com/AndreasBriese/bbloom";
      rev = "28f7e881ca57bc00e028f9ede9f0d9104cfeef5e";
      sha256 = "03cqhqvdz8c9by5w5ls4kwnnwlm6b2kkslc6m120fanw1lgamfzp";
    };
  }
  {
    goPackagePath = "github.com/MakeNowJust/heredoc";
    fetch = {
      type = "git";
      url = "https://github.com/MakeNowJust/heredoc";
      rev = "bb23615498cded5e105af4ce27de75b089cbe851";
      sha256 = "17m780i9afj3sbmcrgwgzarfly4x9376w56qblkqnzdkv6vps22i";
    };
  }
  {
    goPackagePath = "github.com/beorn7/perks";
    fetch = {
      type = "git";
      url = "https://github.com/beorn7/perks";
      rev = "4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9";
      sha256 = "1hrybsql68xw57brzj805xx2mghydpdiysv3gbhr7f5wlxj2514y";
    };
  }
  {
    goPackagePath = "github.com/blevesearch/bleve";
    fetch = {
      type = "git";
      url = "https://github.com/blevesearch/bleve";
      rev = "6eea5b78da004393b1d06b8c88d1bed9ca0a94b2";
      sha256 = "1vv4rjrbgmppr5xcfvfx6fyfzisxlszsxzs90cfsyymymcbqjyhc";
    };
  }
  {
    goPackagePath = "github.com/blevesearch/blevex";
    fetch = {
      type = "git";
      url = "https://github.com/blevesearch/blevex";
      rev = "dfb1a3c92252ad0b5f36b78a0e750ec25d1b67c4";
      sha256 = "12hsywifp4k6jb3ip6vrdf40jw2i19a8yw9ja0xwh5dyyqd425ng";
    };
  }
  {
    goPackagePath = "github.com/blevesearch/go-porterstemmer";
    fetch = {
      type = "git";
      url = "https://github.com/blevesearch/go-porterstemmer";
      rev = "b4dd94e38f29620fe0f97ae4b0f6994b0d5d75f0";
      sha256 = "0q8mi7pr0g7b7k1k6a01xihn2q84cy06gfm53k8jv25r1ndw92rg";
    };
  }
  {
    goPackagePath = "github.com/blevesearch/segment";
    fetch = {
      type = "git";
      url = "https://github.com/blevesearch/segment";
      rev = "762005e7a34fd909a84586299f1dd457371d36ee";
      sha256 = "1nrm145sm0xlhqy3d12yipnb16ikjz9ykjcskmkgm7vjm47xkmfl";
    };
  }
  {
    goPackagePath = "github.com/cockroachdb/cmux";
    fetch = {
      type = "git";
      url = "https://github.com/cockroachdb/cmux";
      rev = "30d10be492927e2dcae0089c374c455d42414fcb";
      sha256 = "0ixif6hwcm2dpi1si5ah49dmdyy5chillz1048jpvjzwzxyfv1nx";
    };
  }
  {
    goPackagePath = "github.com/codahale/hdrhistogram";
    fetch = {
      type = "git";
      url = "https://github.com/codahale/hdrhistogram";
      rev = "3a0bb77429bd3a61596f5e8a3172445844342120";
      sha256 = "1zampgfjbxy192cbwdi7g86l1idxaam96d834wncnpfdwgh5kl57";
    };
  }
  {
    goPackagePath = "github.com/coreos/etcd";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/etcd";
      rev = "f1d7dd87da3e8feab4aaf675b8e29c6a5ed5f58b";
      sha256 = "0ia1hp0bln8vwzamkk50xxc4w9s56q1ib05295zaky2clvs7q14l";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "346938d642f2ec3594ed81d874461961cd0faa76";
      sha256 = "0d4jfmak5p6lb7n2r6yvf5p1zcw0l8j74kn55ghvr7zr7b7axm6c";
    };
  }
  {
    goPackagePath = "github.com/dgraph-io/badger";
    fetch = {
      type = "git";
      url = "https://github.com/dgraph-io/badger";
      rev = "df7b92c78464f24bfa66a0068ecb8b94868aedb2";
      sha256 = "10bmcg0krpw45zkp4ddhbbw6csrkk219mg8sz3ggnizmrb1256j2";
    };
  }
  {
    goPackagePath = "github.com/dgryski/go-farm";
    fetch = {
      type = "git";
      url = "https://github.com/dgryski/go-farm";
      rev = "e2d0fe22b456fa0a35cd883ba355ecfcf1881490";
      sha256 = "1d6rl7vnmr57rwa7xl6dk7lhlxp9ncgs8hrd3b1wh1hydrh1g59x";
    };
  }
  {
    goPackagePath = "github.com/gogo/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/gogo/protobuf";
      rev = "342cbe0a04158f6dcb03ca0079991a51a4248c02";
      sha256 = "1pp1ghicii6f80ygchjqzqswrycpyqhc0m08lrhzyz77ck39cl4q";
    };
  }
  {
    goPackagePath = "github.com/golang/geo";
    fetch = {
      type = "git";
      url = "https://github.com/golang/geo";
      rev = "6fb829cea43026b93220f914ca1043fdbbb35414";
      sha256 = "0jg1x45b50d93sm38bd0s5v1xnrlhy86242938csn3dphidylgmw";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "1643683e1b54a9e88ad26d98f81400c8c9d9f4f9";
      sha256 = "1ch3czyzq5abl6zm1l0dfsi09xj43ql9jcbmbhfhxz954pw03v3v";
    };
  }
  {
    goPackagePath = "github.com/google/codesearch";
    fetch = {
      type = "git";
      url = "https://github.com/google/codesearch";
      rev = "a45d81b686e85d01f2838439deaf72126ccd5a96";
      sha256 = "12bv3yz0l3bmsxbasfgv7scm9j719ch6pmlspv4bd4ix7wjpyhny";
    };
  }
  {
    goPackagePath = "github.com/matttproud/golang_protobuf_extensions";
    fetch = {
      type = "git";
      url = "https://github.com/matttproud/golang_protobuf_extensions";
      rev = "3247c84500bff8d9fb6d579d800f20b3e091582c";
      sha256 = "12hcych25wf725zxdkpnyx4wa0gyxl8v4m8xmhdmmaki9bbmqd0d";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "645ef00459ed84a119197bfb8d8205042c6df63d";
      sha256 = "001i6n71ghp2l6kdl3qq1v2vmghcz3kicv9a5wgcihrzigm75pp5";
    };
  }
  {
    goPackagePath = "github.com/pkg/profile";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/profile";
      rev = "5b67d428864e92711fcbd2f8629456121a56d91f";
      sha256 = "0blqmvgqvdbqmh3fp9pfdxc9w1qfshrr0zy9whj0sn372bw64qnr";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "792786c7400a136282c1664665ae0a8db921c6c2";
      sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_golang";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_golang";
      rev = "c5b7fccd204277076155f10851dad72b76a49317";
      sha256 = "1xqny3147g12n4j03kxm8s9mvdbs3ln6i56c655mybrn9jjy48kd";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_model";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_model";
      rev = "6f3806018612930941127f2a7c6c453ba2c527d2";
      sha256 = "1413ibprinxhni51p0755dp57r9wvbw7xgj9nmdaxmhzlqhc86j4";
    };
  }
  {
    goPackagePath = "github.com/prometheus/common";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/common";
      rev = "1bab55dd05dbff384524a6a1c99006d9eb5f139b";
      sha256 = "02pkl4aqgw02drz1s14a6zqgj607p8lhxrb4a8ygqdkwnidnvfwg";
    };
  }
  {
    goPackagePath = "github.com/prometheus/procfs";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/procfs";
      rev = "a6e9df898b1336106c743392c48ee0b71f5c4efa";
      sha256 = "0zyprdp9bnpywcb6b9dzwyiji60mgf0s9wnw98zndfg3xrgnkasz";
    };
  }
  {
    goPackagePath = "github.com/satori/go.uuid";
    fetch = {
      type = "git";
      url = "https://github.com/satori/go.uuid";
      rev = "879c5887cd475cd7864858769793b2ceb0d44feb";
      sha256 = "1nbydsmjr60904kz5d46nib0zid5kcv4gk9wayi44gn5wlzz80zp";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "69483b4bd14f5845b5a1e55bca19e954e827f1d0";
      sha256 = "11lzrwkdzdd8yyag92akncc008h2f9d1bpc489mxiwp0jrmz4ivb";
    };
  }
  {
    goPackagePath = "github.com/tebeka/snowball";
    fetch = {
      type = "git";
      url = "https://github.com/tebeka/snowball";
      rev = "16e884df4e19660c5d3f61cf70d4a38c9eb1bae4";
      sha256 = "1gqmcp4dqn0677p7kha4rbpf603s0iv5svnzly0k8h9cizgg0brq";
    };
  }
  {
    goPackagePath = "github.com/twpayne/go-geom";
    fetch = {
      type = "git";
      url = "https://github.com/twpayne/go-geom";
      rev = "f8ead8b4672e0bb05caf5ef179962cc7a9f8f876";
      sha256 = "1nf4czzk55046m07a6ncq5sb78q2vl2gmlrdvmilgz38zp0l9451";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "bd6f299fb381e4c3393d1c4b1f0b94f5e77650c8";
      sha256 = "089iwb2wh5mla6hawfbsk8gc6s3vc8j578isyiqfds7j6gc3m5j1";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "01c190206fbdffa42f334f4b2bf2220f50e64920";
      sha256 = "1iqv9pc5846h14cr1nq6prvgxsgj08n36qpd8aqdax1sd9hckysk";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "46eaec7899b1dd945c25db17c78ba3f0c58a6613";
      sha256 = "12s5ckri519j64jxs3v17frw61y7xzvfackf06ccdwgr9kj0pm27";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "88f656faf3f37f690df1a32515b479415e1a6769";
      sha256 = "0zakmgg6dlwnkhignwjajn0dckzqq18zxvnmmg0fq6455x7fs673";
    };
  }
  {
    goPackagePath = "google.golang.org/genproto";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-genproto";
      rev = "03951f3b52582ecab79e5a37a86b5a20c5f64df7";
      sha256 = "1mxqdwn2v19kqf2yj0wwv98jsx2shwgcmjkn9xm62f7iy78x6dl2";
    };
  }
  {
    goPackagePath = "google.golang.org/grpc";
    fetch = {
      type = "git";
      url = "https://github.com/grpc/grpc-go";
      rev = "61d37c5d657a47e4404fd6823bd598341a2595de";
      sha256 = "1rq24f1iknb9raymdjjjpmxs1vwdyr2fq0j5121skgq74dz0ggfv";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "eb3733d160e74a9c7e442f435eb3bea458e1d19f";
      sha256 = "1srhvcaa9db3a6xj29mkjr5kg33y71pclrlx4vcwz5m1lgb5c7q6";
    };
  }
]
